---
- name: add apt keys
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present  

- name: add repository 
  apt_repository: 
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    
- name: package 
  apt: 
    name: google-chrome-stable
    update_cache: yes
    cache_valid_time: 3600      
    state: latest
