---
- name: edit bashrc file
  blockinfile:
    marker: "# {mark} IMPORT CUSTOM"
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      if [ -f ~/.bash_custom ]; then
        . ~/.bash_custom
      fi

- name: template aliases
  template:
    src: "./templates/aliases.j2"
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    owner: "{{ user }}"
    group: "{{ user }}"
    force: yes

- name: template custom
  template:
    src: "./templates/custom.j2"
    dest: "{{ ansible_env.HOME }}/.bash_custom"
    owner: "{{ user }}"
    group: "{{ user }}"
    force: no

