---
- name: packages
  apt:
    name: "{{ item }}"
    state: latest   
    update_cache: yes
    cache_valid_time: 3600
  with_items:  
    - mediainfo 
    - vlc
    - gnome-mpv
    - deluge
    - deluged

    - geany
    - git       
    - vim

    - hexchat
    - hexchat-indicator 
    - sshfs

    - nfs-common 
    - nfs-kernel-server         
    - apt-transport-https 
    - software-properties-common 
    - ca-certificates 
    - curl
    - wget        

    - python-pip
    - python-setuptools

    - unrar
    - rar
    - zip

    - htop