---
- name: packages
  apt:
    name: 
    - gnome-panel 
    - gnome-flashback 
    - gnome-session-flashback 
    - indicator-applet-appmenu
    
    state: latest   
    update_cache: yes
    cache_valid_time: 3600
