---
- name: packages
  apt:
    name: "{{ item }}"
    state: latest   
    update_cache: yes
    cache_valid_time: 3600
  with_items:  
    - gnome-panel 
    - gnome-flashback 
    - gnome-session-flashback 
    - indicator-applet-appmenu
