---
- name: role bash
  import_role:
    name: bash

- name: php  7.2
  apt:
    name: 
    - php7.2-cli
    - libpcre3-dev
    - php7.2-gd
    - php7.2-curl
    - php7.2-imap
    - php7.2-json
    - php7.2-opcache
    - php7.2-xml
    - php7.2-zip
    - php7.2-mbstring
    - php-xdebug
    - php-apcu
    - build-essential
    - php7.2-dev    
    state: latest
    update_cache: yes
    cache_valid_time: 3600


- name: composer
  import_role:
    name: geerlingguy.composer
  vars:
    - composer_home_owner: "{{ user }}"
    - composer_home_group: "{{ user }}"


- name: edit bashrc file
  blockinfile:
    marker: "# {mark} COMPOSER SHELL"
    path: "{{ ansible_env.HOME }}/.bash_custom"
    block: |
      export COMPOSER_HOME=$HOME/.composer
      export COMPOSER_CACHE_DIR=$COMPOSER_HOME/cache
      export PATH=$PATH:$COMPOSER_HOME/vendor/bin
      

