---
- name: fonts
  apt:
    name: "fonts-powerline"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: powerline shell
  pip:
    name: "powerline-shell"


- name: powerline shell config
  template:
    src: "./templates/powerline-shell.json.j2"
    dest: "{{ ansible_env.HOME }}/.powerline-shell.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    force: no
