---
- name: fonts
  apt:
    name: "fonts-powerline"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: powerline shell
  pip:
    name: "powerline-shell"


- name: powerline shell config
  template:
    src: "./templates/powerline-shell.json.j2"
    dest: "{{ ansible_env.HOME }}/.powerline-shell.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    force: no


- name: edit bashrc file
  blockinfile:
    marker: "# {mark} POWERLINE SHELL"
    path: "{{ ansible_env.HOME }}/.bash_custom"
    block: |
      function _update_ps1() {
          PS1=$(powerline-shell $?)
      }

      if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
          PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi

