---
- name: packages
  apt:
    name: "{{ item }}"
    state: latest   
    update_cache: yes
    cache_valid_time: 3600
  with_items:  
    - powerline 
    - python3-powerline
    - fonts-powerline

- name: config
  git:
    repo: "https://github.com/adidenko/powerline.git"
    dest: "{{ ansible_env.HOME }}/.config/powerline"
