---
- name: role bash
  import_role:
    name: bash

- name: role packages
  import_role:
    name: packages

- name: apt_key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable"

- name: packages
  apt:
    name: 
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce    
    update_cache: yes
    cache_valid_time: 3600
    state: latest


- name: add user
  command: usermod -aG docker {{ user }}



- name: docker-compose
  command: usermod -aG docker {{ user }}

#
#
#- name: Installing dependencies
#  easy_install:
#    name: pip

- name: Installing docker compose
  pip:
    name: docker-compose
