---
- hosts: all
  vars:
    user: pato
    group: pato
  become: true
  become_user: root
  become_method: sudo
  tasks:
  
    - name: Add Apt Keys
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
        state: present  
        
    - name: Add Apt Repositories    
      apt_repository: repo='deb http://repository.spotify.com stable non-free'
  
  
    - name: Gnome Classsic
      apt:
        name: "{{ item }}"
        state: latest   
        update_cache: yes
        cache_valid_time: 3600
      with_items:  
        - gnome-panel 
        - gnome-flashback 
        - gnome-session-flashback 
        - indicator-applet-appmenu
          
    - name: Basic packages
      apt:
        name: "{{ item }}"
        state: latest   
        update_cache: yes
        cache_valid_time: 3600
      with_items:  
        - geany
        - git       
        - vim
        - tilix        
        - hexchat 
        - hexchat-indicator 
        - sshfs
        
    - name: Puesta a punto
      apt:
        name: "{{ item }}"
        state: latest   
        update_cache: yes
        cache_valid_time: 3600
      with_items:          
        - nfs-common 
        - nfs-kernel-server         
        
    - name: Multimedia
      apt:
        name: "{{ item }}"
        state: latest   
        update_cache: yes
        cache_valid_time: 3600
      with_items:  
        - mediainfo 
        - vlc
        - spotify-client
        - deluge
        - deluged
        
        
    - name: comandos    
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}" 
        
      with_items:  
        - {src: './templates/osmc.j2', dest: '/home/{{ user }}/bin/osmc', owner: 'pato', group: 'pato', mode: '0755'}
